- hosts: all
  # strategy: debug  ## interactive debug console when a task fails.
  roles:
    - gather_custom_facts
    - upgrade
    - {role: prepare, when: "ansible_local['prepare_facts']['has_prepare_passed'] == false" }
    - {role: utilities, when: "ansible_local['utilities_facts']['has_utilities_passed'] == false" }
    - {role: suricata, when: "ansible_local['suricata_facts']['has_suricata_installed'] == false" }
    - {role: sysstat, when: "ansible_local['sysstat_facts']['has_sysstat_passed'] == false" }
    - {role: set-sysctl, when: "ansible_local['set-sysctl_facts']['has_set-sysctl_passed'] == false" }
    - reboot
    - {role: get-sysctl, when: "ansible_local['get-sysctl_facts']['has_get-sysctl_passed'] == false" }
    - {role: docker, when: "ansible_local['docker_facts']['has_docker_installed'] == false" }
    - fail2ban
    - auth
    - {role: tmux, when: "ansible_local['tmux_facts']['has_tmux_installed'] == false" }
    - timezone
    - ntp
    #- host_metrics
    #- dotfiles
    - services
    #- firewalld
    #- cleanup
    #- reboot
    #- start_containers
