- hosts: all
  # strategy: debug  ## interactive debug console when a task fails.
  roles:
    - upgrade
    - prepare
    - utilities
    - {role: suricata, when: ">>> ansible fact here <<< == false" }
    # - sysstat
    # - set-sysctl
    # - reboot
    # - get-sysctl
    #- docker
    #- fail2ban
    #- auth
    #- tmux
    #- timezone
    #- ntp
    #- host_metrics
    #- dotfiles
    #- services
    #- firewalld
    #- cleanup
    #- reboot
    #- start_containers
