- hosts: all
  # strategy: debug  ## interactive debug console when a task fails.
  roles:
    - gather_custom_facts
    - upgrade
    - {role: prepare, when: "ansible_local['prepare_facts']['has_prepare_passed'] == false" }
    - utilities
    - {role: suricata, when: "ansible_local['suricata_facts']['has_suricata_installed'] == false" }
    - sysstat
    - set-sysctl
    - reboot
    - get-sysctl
    - {role: docker, when: "ansible_local['docker_facts']['has_docker_installed'] == false" }
    - fail2ban
    - auth
    - {role: tmux, when: "ansible_local['tmux_facts']['has_tmux_installed'] == false" }
    - timezone
    - ntp
    #- host_metrics
    #- dotfiles
    - services
    #- firewalld
    #- cleanup
    #- reboot
    #- start_containers
