#!/bin/bash
#
# Hook script for QEMU
#
# adds port forwards via IPtables to your VMs
#
# Erico Mendonca (erico.mendonca@suse.com)
# dec/2018
#
# https://github.com/doccaz/kvm-scripts
#
# reference: https://wiki.libvirt.org/page/Networking#Forwarding_Incoming_Connections
#
# Adapted by Branislav Siarsky
# apr/2020
# 
# Adapted by Tiago Paranhos Lima
# jul/2020

log() {
        echo "$1" | systemd-cat -t qemu-addForward
}

addForward() {
   VM=$1
   HOST_NIC=$2
   HOST_IP=$3
   HOST_PORT=$4
   GUEST_NIC=$5
   GUEST_IP=$6
   GUEST_PORT=$7

   IPTABLES="sudo iptables"
   IP="sudo ip"
   HOST_IP_MASK="24"
   IPTABLES_ACTION=""
   IPTABLES_TEXT=""
   IP_ACTION=""
   IP_TEXT=""

   if [ "${VM}" == "${VM_NAME}" ]; then
	   log "ACTION = ${ACTION}"
	   if [ "${ACTION}" == "stopped" ] || [ "${ACTION}" == "reconnect" ]; then
		   IPTABLES_ACTION="-D"
		   IPTABLES_TEXT="Removing forwarding rules for VM ${VM}"
		   IP_ACTION="del"
		   IP_TEXT="Removing IP ${HOST_IP} from ${HOST_NIC}"
	   fi

	   if [ "${ACTION}" == "start" ] || [ "${ACTION}" == "reconnect" ]; then
		   IPTABLES_ACTION="-I"
		   IPTABLES_TEXT="Adding forwarding rules for VM ${VM}: host port ${HOST_PORT} will be redirected to ${GUEST_IP}:${GUEST_PORT} on interface ${GUEST_NIC}"
		   IP_ACTION="add"
		   IP_TEXT="Adding IP ${HOST_IP} to ${HOST_NIC}"
	   fi

	   if [ "${IPTABLES_ACTION}" == "" ]; then
		   log "Action ${ACTION} on domain $VM not configured, ignoring"
		   exit 0
	   else
		   log "Action ${ACTION} on domain $VM called"
	   fi

	   log "${IPTABLES_TEXT}"
	   $IPTABLES ${IPTABLES_ACTION} FORWARD -o ${GUEST_NIC} -p tcp -d $GUEST_IP --dport $GUEST_PORT -j ACCEPT
	   $IPTABLES -t nat ${IPTABLES_ACTION} PREROUTING -p tcp --dport $HOST_PORT -j DNAT --to $GUEST_IP:$GUEST_PORT

	   log "${IP_TEXT}"
	   $IP address ${IP_ACTION} ${HOST_IP}/${HOST_IP_MASK} dev ${HOST_NIC}
   fi
}

## main program
VM_NAME=${1}
ACTION=${2}

### declare your port forwards here
### format: addForward <VM> <source nic> <source address> <source port> <destination nic> <destination address> <destination port>
#Port 80 forward:   addForward debian10-vm2 enp3s0f0 192.168.1.17 80 virbr0 192.168.122.2 80
#All ports forward: addForward debian10-vm2 enp3s0f0 192.168.1.17 1:65535 virbr0 192.168.122.2 1-65535
addForward ubuntu18-k3s wlp2s0 192.168.100.141 14601 virbr0 192.168.122.251 9000
# addForward ubuntu18-k3s wlp2s0 192.168.100.141 14602 virbr0 192.168.122.251 8001

