#!/bin/bash
# KVM NETWORK TYPE: nat

IPTABLES="sudo iptables"

KVM_BRIDGE_NIC=virbr0
VM_NETWORK=192.168.122.0/24
VM_IP=192.168.122.251
VM_PORT=9000
HOST_PORT=10090
HOST_NETWORK_DEVICE=wlp2s0

# connections from outside
$IPTABLES -I FORWARD -o $KVM_BRIDGE_NIC -d $VM_IP -j ACCEPT
$IPTABLES -t nat -I PREROUTING -p tcp --dport $HOST_PORT -j DNAT --to $VM_IP:$VM_PORT

# Masquerade local subnet
$IPTABLES -I FORWARD -o $KVM_BRIDGE_NIC -d $VM_IP -j ACCEPT
$IPTABLES -t nat -A POSTROUTING -s $VM_NETWORK -j MASQUERADE
$IPTABLES -A FORWARD -o $KVM_BRIDGE_NIC -m state --state RELATED,ESTABLISHED -j ACCEPT  # maybe add state NEW too
$IPTABLES -A FORWARD -i $KVM_BRIDGE_NIC -o $HOST_NETWORK_DEVICE -j ACCEPT
$IPTABLES -A FORWARD -i $KVM_BRIDGE_NIC -o lo -j ACCEPT
