- name: Set timezone
  command: "{{item}}" 
  with_items:  # this is the only way to run more than one command with the ansible "command" module
      - timedatectl set-timezone America/Sao_Paulo
      - timedatectl  

