- name: Copy suricata installation script
  template:     
    src: install.sh.j2
    dest: /tmp/install.sh
    mode: 0777

- name: Run installation script
  command: /tmp/install.sh

- name: Copy suricata configuration file
  copy: src=files/suricata.yaml dest=/etc/suricata backup=yes owner=suri group=suri mode=0600

- name: Copy systemd service unit file 
  copy: src=files/suricata.service dest=/etc/systemd/system mode=0600

- name: Copy logrotate file 
  copy: src=files/suricata.logrotate dest=/etc/logrotate.d/suricata mode=0644

- name: Install suricata-update
  pip: name=suricata-update

