- name: Create the folder to download netdata installation script to
  file:
    path: /opt/netdata-installer
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Download netdata installation script
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /opt/netdata-installer
    mode: 0744

- name: Run the installation script
  command: bash /opt/netdata-installer/kickstart.sh --dont-wait --non-interactive

- name: Generate file to verify it passed through this role
  lineinfile:
    dest: /var/log/netdata_passed.txt
    line: "{{ ansible_date_time.iso8601 }}"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644

