- name: Enable and start all services
  systemd: name={{item}} daemon-reload=yes state=started enabled=yes
  with_items:
    - suricata
    - suricata-update.timer
    #    - docker
    #    - fail2ban
    #    - sshd
    #    - ntpd
    #    - auditd
    #    - collectd
    #    - influxdb
