# This is an example configuration for Docker Compose. Make sure to atleast update
# the cookie secret & postgres database password.
#
# Some other recommendations:
# 1. To persist Postgres data, assign it a volume host location.
# 2. Split the worker service to adhoc workers and scheduled queries workers.
version: '2'
services:
  server:
    image: redash/redash:latest
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_COOKIE_SECRET: veryverysecret
      REDASH_WEB_WORKERS: 4
    restart: always
  worker:
    image: redash/redash:latest
    command: scheduler
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://redash:r3da5h@postgres/redash"
      QUEUES: "queries,scheduled_queries,celery"
      WORKERS_COUNT: 2
    restart: always
  redis:
    hostname: redis
    image: redis:3.0-alpine
    restart: always
  postgres:
    hostname: postgres
    image: postgres:9.5.6-alpine
    volumes:
      - POSTGRESQL_DATA:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_USER=redash
      - POSTGRES_PASSWORD=r3da5h
      - POSTGRES_DB=redash
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:8555"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
volumes:
  POSTGRESQL_DATA:
    driver: local

