- name: Install additional utilities 
  yum: pkg={{item}} state=installed update_cache=true
  with_items:
      - vim
      - ncdu
      - bash-completion
      - bash-completion-extras  
      - tree
      - sysstat
      - iotop
      - siege
      - curl
      - wget
      - links
      - elinks
      - htop
      - lsof
      - tcpdump
      - nmap
      - git
      - rsync

