- hosts: all
  # strategy: debug  ## interactive debug console when a task fails.
  roles:
    - gather_custom_facts
    - upgrade
    - {role: traefik, when: "ansible_local['traefik_facts']['has_traefik_installed'] == false" }
    - services
    - reboot
    - cleanup
