---
- hosts: all 
  tasks:
      - name: upgrade all packages
        yum: name=* state=latest

      - name: Install epel-release
        yum: pkg=epel-release state=installed update_cache=true  

      - name: Add portainer init script
        copy: src=files/run_portainer.sh dest=/opt owner=root group=root mode=0777

      - name: Install docker
        yum: pkg=docker state=installed update_cache=true
        notify:
            - Configure docker daemon
            - Start docker
            - Start portainer
            - Check portainer passwd
            - Print portainer passwd

      - name: Install python-pip
        yum: pkg=python-pip state=installed update_cache=true

      - name: Install docker-compose
        pip: name=docker-compose    

      - name: Install rsyslog
        yum: pkg=rsyslog state=installed update_cache=true
        notify:
            - Start rsyslog  # handler to be called below        

      - name: Install pyinotify  # requirement to fail2ban
        pip: name=pyinotify    

      - name: Install fail2ban
        yum: pkg=fail2ban state=installed update_cache=true

      - name: Add fail2ban config
        copy: src=files/jail.local dest=/etc/fail2ban owner=root group=root
        notify:
            - Start fail2ban

      - name: Install vim 
        yum: pkg=vim state=installed update_cache=true

      - name: install tmux
        yum: pkg=tmux state=installed update_cache=true

  handlers:
      - name: Configure docker daemon
        copy: src=files/daemon.json dest=/etc/docker owner=root group=root

      - name: Start docker
        service: name=docker state=started

      - name: Start rsyslog
        service: name=rsyslog state=started
  
      - name: Start fail2ban
        service: name=fail2ban state=started
  
      - name: Start portainer
        command: bash /opt/run_portainer.sh

      - name: Check portainer passwd
        command: /bin/cat /root/portainer.admin.passwd
        register: password  # record the command stdout to the "password" variable
        changed_when: False  # this make this task always run

      - name: Print portainer passwd
        debug: var=password.stdout  # prints the value of the "password" variable

