---
- hosts: all 
  tasks:
      - name: upgrade all packages
        yum: name=* state=latest

      - name: Install epel-release
        yum: pkg=epel-release state=installed update_cache=true  

      - name: Install docker
        yum: pkg=docker state=installed update_cache=true
        notify:
            - Start docker  # handler to be called below

      - name: Install python-pip
        yum: pkg=python-pip state=installed update_cache=true

      - name: Install docker-compose
        pip: name=docker-compose    

      - name: Install rsyslog
        yum: pkg=rsyslog state=installed update_cache=true
        notify:
            - Start rsyslog  # handler to be called below        

  handlers:
      - name: Start docker
        service: name=docker state=started

      - name: Start rsyslog
        service: name=rsyslog state=started
  
