---
- hosts: all 
  tasks:
      - name: upgrade all packages
        yum: name=* state=latest

      - name: Install epel-release
        yum: pkg=epel-release state=installed update_cache=true  

      - name: Add portainer init script
        copy: src=files/run_portainer.sh dest=/opt owner=root group=root mode=0777

      - name: Install docker
        yum: pkg=docker state=installed update_cache=true

      - name: Start docker
        service: name=docker state=started

      - name: Run docker version
        command: docker version
        register: dockerversion
        changed_when: False  # this make this task always run

      - name: Print docker version
        debug: var=dockerversion.stdout

      - name: Run docker info
        command: docker info
        register: dockerinfo
        changed_when: False  # this make this task always run

      - name: Print docker info
        debug: var=dockerinfo.stdout

      - name: Start portainer
        command: bash /opt/run_portainer.sh

      - name: Check portainer passwd
        command: /bin/cat /root/portainer.admin.passwd
        register: password  # record the command stdout to the "password" variable
        changed_when: False  # this make this task always run

      - name: Print portainer passwd
        debug: var=password.stdout  # prints the value of the "password" variable

      - name: Install python-pip
        yum: pkg=python-pip state=installed update_cache=true

      - name: Install docker-compose
        pip: name=docker-compose    

      - name: Install pyinotify  # requirement to fail2ban
        pip: name=pyinotify    

      - name: Install fail2ban
        yum: pkg=fail2ban state=installed update_cache=true

      - name: Add fail2ban config
        copy: src=files/jail.local dest=/etc/fail2ban owner=root group=root
        notify:
            - Start fail2ban

      - name: Install additional utilities 
        yum: pkg={{item}} state=installed update_cache=true
        with_items:
            - vim
            - tmux
            - ncdu 
            - tree
            - sysstat
            - iotop
            - siege
            - curl
            - wget
            - links
            - elinks
            - htop
            - dstat
            - lsof
            - tcpdump
            - nmap
            - git
            - rsync

      - name: Create user
        user: name=dev 
              shell=/bin/bash 
              home=/home/dev 
              groups=dockerroot,users,input 
              generate_ssh_key=yes 
              ssh_key_bits=2048

      - name: Get ssh public key
        command: /bin/cat /home/dev/.ssh/id_rsa.pub
        register: cat
        changed_when: False
      
      - name: Print ssh public key
        debug: var=cat.stdout      

      - name: Authorize the ssh key from this ansible host to the dev user.
        authorized_key:
            user: dev
            state: present
            key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

  handlers:
      - name: Start fail2ban
        service: name=fail2ban state=started
