- name: Download recent tmux
  become_user: ops
  get_url:
      url: https://raw.githubusercontent.com/tiagoprn/devops/master/shellscripts/installers/install_tmux_on_home_folder.sh
      dest: /home/ops/install_tmux.sh
      mode: 0500

- name: Install downloaded tmux
  become_user: ops
  command: /bin/bash /home/ops/install_tmux.sh

