# https://www.youtube.com/watch?v=BWPOLLC1TE8

- name: Create configuration folder
  file:
    path: /etc/alertmanager
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0775
    recurse: yes

- name: Create support folder
  file:
    path: /var/lib/alertmanager/data
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0775
    recurse: yes

- name: Create download folder
  file:
    path: /opt/alertmanager-installer
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: yes

- name: Download alertmanager release
  get_url:
    url: https://github.com/prometheus/alertmanager/releases/download/v{{ download_version }}/alertmanager-{{ download_version }}.linux-amd64.tar.gz
    dest: /opt/alertmanager-installer/alertmanager-{{ download_version }}.linux-amd64.tar.gz
    mode: 0744

- name: Extract the downloaded release
  unarchive:
    src: /opt/alertmanager-installer/alertmanager-{{ download_version }}.linux-amd64.tar.gz
    dest: /opt/alertmanager-installer
    remote_src: yes

- name: copy alertmanager binary to system binaries
  copy: src=/opt/alertmanager-installer/alertmanager-{{ download_version }}.linux-amd64/alertmanager dest=/usr/local/bin/alertmanager owner=prometheus group=prometheus mode=0744 remote_src=yes

- name: copy amtool binary to system binaries
  copy: src=/opt/alertmanager-installer/alertmanager-{{ download_version }}.linux-amd64/amtool dest=/usr/local/bin/amtool owner=prometheus group=prometheus mode=0744 remote_src=yes

- name: copy alertmanager configuration to its' configuration folder
  template:
    src: config.yml.j2
    dest: /etc/alertmanager/config.yml
    owner: prometheus
    group: prometheus

- name: copy alertmanager service to systemd unit files path
  copy: src=files/alertmanager.service dest=/etc/systemd/system/alertmanager.service owner=root group=root

- name: compile the alert rule file
  shell: promtool check rules /etc/prometheus/alert.rules

- name: copy the email notification alert template to its path
  copy: src=files/alert.tmpl dest=/etc/prometheus/alert.tmpl owner=prometheus group=prometheus

- name: Enable and start alertmanager service
  systemd: name=alertmanager daemon-reload=yes state=started enabled=yes

- name: Generate file to verify it passed through this role
  lineinfile:
    dest: /var/log/alertmanager_passed.txt
    line: "{{ ansible_date_time.iso8601 }}"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
