- name: Enable all services 
  service: name={{item}} enabled=yes
  with_items:
      - docker 
      - fail2ban
      - sshd
      - ntpd
      - auditd  
      - collectd
      - influxdb
      - grafana-server
