session_name: DEV
windows:
  - window_name: main
    layout: even-vertical
    start_directory: /storage/src
    shell_command_before:
      - source "$(navi widget bash)"
      - pyenv deactivate utils
      - clear
      - source ~/.bash_environment || true && source ~/.bash_profile || true && source ~/.bash_functions && source ~/.bash_aliases
    panes:
      - cd dot_files && clear
      - cd devops && clear
      - clear

