global:
  # The smarthost and SMTP sender used for mail notifications.
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

route:
  receiver: "default"
  routes:
   - match:
      severity: info
     receiver: email

   - match:
      severity: critical
     receiver: email
     group_wait: 30s
     group_interval: 5m
     repeat_interval: 5m

receivers:
  - name: default
    email_configs:
     - to: 'to@youremail.com'
       html: '{{ template "email" .}}'

  - name: email
    email_configs:
     - to: 'to@youremail.com'
       html: '{{ template "email" .}}'

templates:
- '/etc/prometheus/alert.tmpl'
