- name: Add portainer init script
  copy: src=files/run_portainer.sh dest=/opt owner=root group=root mode=0777

- name: Install docker pkg requirements
  yum: pkg={{item}} state=installed update_cache=true
  with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

- name: Download docker-ce repository
  get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo 
      dest: /etc/yum.repos.d/docker-ce.repo

- name: Install docker
  yum: pkg=docker-ce state=installed update_cache=true

- name: Start docker
  service: name=docker state=started

- name: Add docker config (logging driver and log format)
  copy: src=files/docker-daemon.json dest=/etc/docker/daemon.json owner=root group=root

- name: Restart docker
  service: name=docker state=restarted

- name: Run docker version
  command: docker version
  register: dockerversion
  changed_when: False  # this make this task always run

- name: Print docker version
  debug: var=dockerversion.stdout

- name: Run docker info
  command: docker info
  register: dockerinfo
  changed_when: False  # this make this task always run

- name: Print docker info
  debug: var=dockerinfo.stdout

- name: Start portainer
  command: bash /opt/run_portainer.sh

- name: Check portainer passwd
  command: /bin/cat /root/portainer.admin.passwd
  register: password  # record the command stdout to the "password" variable
  changed_when: False  # this make this task always run

- name: Print portainer passwd
  debug: var=password.stdout  # prints the value of the "password" variable

- name: Install docker-compose
  pip: name=docker-compose    

