- name: Install additional development libraries/tools
  action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
      - build-essential
        # - bind-utils
        #- python-pip
        # - libnet
        # - libpcap-devel
        # - libnet-devel
        # - pcre-devel
        # - libnet-devel
        # - libyaml-devel
        # - zlib-devel
        # - file-devel
        # - libcap-devel
        # - libcap-ng-devel

