- name: Create custom fact directory to allow storing custom facts to be read by any playbook
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Insert prepare role fact file
  copy:
    src: files/prepare_facts.fact
    dest: /etc/ansible/facts.d/prepare_facts.fact
    mode: 0755

- name: Insert utilities role fact file
  copy:
    src: files/utilities_facts.fact
    dest: /etc/ansible/facts.d/utilities_facts.fact
    mode: 0755

- name: Insert sysstat role fact file
  copy:
    src: files/sysstat_facts.fact
    dest: /etc/ansible/facts.d/sysstat_facts.fact
    mode: 0755

- name: Insert suricata fact file
  copy:
    src: files/suricata_facts.fact
    dest: /etc/ansible/facts.d/suricata_facts.fact
    mode: 0755

- name: Insert docker fact file
  copy:
    src: files/docker_facts.fact
    dest: /etc/ansible/facts.d/docker_facts.fact
    mode: 0755

- name: Insert tmux fact file
  copy:
    src: files/tmux_facts.fact
    dest: /etc/ansible/facts.d/tmux_facts.fact
    mode: 0755

- name: Reload ansible local vars, to have the installed fact available to use
  setup: filter=ansible_local

- name: show ansible_local dict values
  debug:
    var: ansible_local
    verbosity: 1
