database:
  image: mysql:5.6 
  volumes:
    - "./shared:/shared"
    - "./utils:/utils"
  expose:
    - 3306
  ports:
    - "3306:3306"
  environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=true  
    - MYSQL_USER=tester
    - MYSQL_PASSWORD=12345678  
    - MYSQL_DATABASE=local_db
