database:
  image: mysql 
  volumes:
    - "./shared:/shared"
    - "./utils:/utils"
  expose:
    - 3306
  ports:
    - "3306:3306"
  environment:
    - MYSQL_USER=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=sampledb
