#!/bin/bash

# Shows if dunst notifications are paused.

if [ -x "$(command -v tput)" ]; then
	bold="$(tput bold)"
	black="$(tput setaf 0)"
	red="$(tput setaf 1)"
	green="$(tput setaf 2)"
	yellow="$(tput setaf 3)"
	blue="$(tput setaf 4)"
	magenta="$(tput setaf 5)"
	cyan="$(tput setaf 6)"
	white="$(tput setaf 7)"
	reset="$(tput sgr0)"
fi

ON="${reset}${bold}${blue}"
OFF="${reset}${bold}${red}"
RESET="${reset}"

IS_PAUSED=$(dunstctl is-paused)

if [ "$IS_PAUSED" == 'true' ]; then
    STATUS="${OFF}   ${RESET}"
else
    STATUS="${ON}   ${RESET}"
fi

echo -e "$STATUS"
