version: "3"
services:
  database:
    image: mysql:latest
    container_name: mysql_docker
    volumes:
      - "./shared:/shared"
      - "./utils:/utils"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=tester
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=local_db
