- name: Get sysctl configuration
  command: sysctl -a
  register: sysctl
  changed_when: False  # this make this task always run

- name: Print sysctl configuration
  debug: var=sysctl.stdout


- name: Generate file to verify it passed through this role
  lineinfile:
    dest: /var/log/get-sysctl_passed.txt
    line: "{{ ansible_date_time.iso8601 }}"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
