# TODO: adapt here to intructions from:
# - https://github.com/SushiFu/traefik-local
# - https://www.grzegorowski.com/page/

- name: Run docker version
  command: docker version
  register: dockerversion
  changed_when: False  # this make this task always run

- name: Create the folder to hold portainer compose file and start/stop scripts
  file:
    path: /opt/containers/portainer
    state: directory
    owner: root
    group: root
    mode: 0775
    recurse: yes

- name: Add portainer start script
  copy: src=files/start.sh dest=/opt/containers/portainer owner=root group=root mode=0777

- name: Add portainer stop script
  copy: src=files/stop.sh dest=/opt/containers/portainer owner=root group=root mode=0777

- name: Generate the TLS certificates
  command: bash /opt/create-csr-and-private-key.sh -o /certificates/portainer

- name: Generate a random password for portainer admin user
  command: bash /opt/random_password.sh
  register: portainer_password  # record the command stdout to the "password" variable
  changed_when: False  # this make this task always run

- name: Print portainer admin user passwd
  debug: var=portainer_password.stdout  # prints the value of the "password" variable

- name: Copy the portainer admin password to a file
  copy: content="{{ portainer_password.stdout }}" dest="/opt/containers/portainer/admin.passwd"

- name: Create the docker-compose file for portainer
  template:
    src: docker-compose.yml.j2
    dest: /opt/containers/portainer/docker-compose.yml
    owner: root
    group: root
    mode: 0700
    backup: yes

- name: Start portainer
  command: bash /opt/containers/portainer/start.sh

# below is already adapted to traefik

- name: Generate file to verify it passed through this role
  lineinfile:
    dest: /var/log/traefik_passed.txt
    line: "{{ ansible_date_time.iso8601 }}"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644

