- name: Install additional utilities
  action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
      - vim
      - ncdu
      - bash-completion
      - tree
      - sysstat
      - iotop
      - siege
      - curl
      - wget
      - links
      - elinks
      - htop
      - lsof
      - tcpdump
      - nmap
      - git
      - rsync
      - ioping
      - man-db
      - manpages
      - unzip
      - stress-ng

- name: Copy file to verify it passed through this role
  copy: src=files/passed.txt dest=/var/log/utilities_passed.txt owner=root group=root mode=0644
