version: '2'
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    privileged: true
    restart: unless-stopped
    command: --admin-password-file "/tmp/admin.passwd" --host=unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/localtime:/etc/localtime"
      - "./shared/admin.passwd:/tmp/admin.passwd"
      - PORTAINER_DATA:/data
volumes:
  PORTAINER_DATA:
    driver: local
