--
-- PostgreSQL database dump
--

-- Dumped from database version 10.4 (Debian 10.4-2.pgdg90+1)
-- Dumped by pg_dump version 10.4 (Debian 10.4-2.pgdg90+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: visualizations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.visualizations VALUES ('2018-07-06 22:09:15.115832+00', '2018-07-06 22:09:15.115832+00', 1, 'TABLE', 1, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:14:35.412813+00', '2018-07-06 22:14:35.412813+00', 3, 'TABLE', 2, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:35:59.140635+00', '2018-07-06 22:35:59.140635+00', 5, 'TABLE', 3, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 7, 'CHART', 3, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:33.480086+00', '2018-07-06 22:39:33.480086+00', 8, 'TABLE', 4, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 10, 'CHART', 4, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:42:18.588062+00', '2018-07-06 22:42:18.588062+00', 12, 'TABLE', 5, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 14, 'CHART', 5, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:45:28.273363+00', '2018-07-06 22:45:28.273363+00', 16, 'TABLE', 6, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:54:36.88336+00', '2018-07-06 22:54:36.88336+00', 20, 'TABLE', 8, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 22, 'CHART', 8, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:02:34.739878+00', '2018-07-06 23:02:34.739878+00', 23, 'TABLE', 9, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 24, 'CHART', 9, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:05:38.263754+00', '2018-07-06 23:05:38.263754+00', 25, 'TABLE', 10, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 26, 'CHART', 10, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:09:06.858147+00', '2018-07-06 23:09:06.858147+00', 29, 'TABLE', 12, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:10:34.222101+00', '2018-07-06 23:10:34.222101+00', 31, 'TABLE', 13, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:15:10.01072+00', '2018-07-06 22:15:10.01072+00', 4, 'CHART', 2, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value_in_mb": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value_in_mb": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:07:38.871851+00', '2018-07-06 23:07:38.871851+00', 27, 'TABLE', 11, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 28, 'CHART', 11, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:11:06.126959+00', '2018-07-06 22:11:06.126959+00', 2, 'CHART', 1, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value_in_mb": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value_in_mb": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 17, 'CHART', 6, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:47:11.532833+00', '2018-07-06 22:47:11.532833+00', 18, 'TABLE', 7, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 19, 'CHART', 7, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 30, 'CHART', 12, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 32, 'CHART', 13, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');


--
-- Name: visualizations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.visualizations_id_seq', 32, true);


--
-- PostgreSQL database dump complete
--

