# https://www.youtube.com/watch?v=OnzIUGHl9no&t=979s

- name: Create download folder
  file:
    path: /opt/node_exporter-installer/conf
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: yes

- name: Download node_exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ download_version }}/node_exporter-{{ download_version }}.linux-amd64.tar.gz
    dest: /opt/node_exporter-installer/node_exporter-{{ download_version }}.linux-amd64.tar.gz
    mode: 0744

- name: Extract the downloaded release
  unarchive:
    src: /opt/node_exporter-installer/node_exporter-{{ download_version }}.linux-amd64.tar.gz
    dest: /opt/node_exporter-installer
    remote_src: yes

- name: copy node_exporter binary to system binaries
  copy: src=/opt/node_exporter-installer/node_exporter-{{ download_version }}.linux-amd64/node_exporter dest=/usr/local/bin/node_exporter owner=prometheus group=prometheus mode=0744 remote_src=yes

- name: copy node_exporter service to systemd unit files path
  copy: src=files/node_exporter.service dest=/etc/systemd/system/node_exporter.service owner=root group=root

- name: Enable and start node_exporter service
  systemd: name=node_exporter daemon-reload=yes state=started enabled=yes

- name: copy node_exporter prometheus configuration to be merged to it later
  copy: src=files/prometheus-node_exporter.scrapper.yml dest=/opt/node_exporter-installer/conf/prometheus-node_exporter.scrapper.yml owner=root group=root

- name: update prometheus configuration with node-exporter configuration
  shell: cat /opt/node_exporter-installer/conf/prometheus-node_exporter.scrapper.yml >> /etc/prometheus/prometheus.yml

- name: Stop prometheus service to apply the new configuration
  systemd: name=prometheus daemon-reload=yes state=stopped enabled=yes

- name: (Re)start prometheus service to apply the new configuration
  systemd: name=prometheus daemon-reload=yes state=started enabled=yes

- name: Generate file to verify it passed through this role
  lineinfile:
    dest: /var/log/node_exporter_passed.txt
    line: "{{ ansible_date_time.iso8601 }}"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644
