- name: Build and first start of the redash container
  become: yes
  shell: "make run 2>&1"
  args:
    executable: /bin/bash
    chdir: /opt/containers/redash

- name: Restore redash container metrics
  become: yes
  shell: "make restore_redash_collectd_metrics 2>&1"
  args:
    executable: /bin/bash
    chdir: /opt/containers/redash
