version: '2'                                        
services:                                           
  ansible:                                          
    image: tiagoprn/ansible2:20170701-2
    container_name: ansible
    command: tail -f /dev/null  # to keep running forever    
    restart: on-failure                                 
    network_mode: "host"                            
    pid: "host"                                     
    privileged: true                                
    volumes:                                        
      - /etc/localtime:/etc/localtime
      - ./filesystem/conf:/etc/ansible
      - ../../ansible_playbooks:/etc/ansible/playbooks  
      - ./shared:/shared
      - /home/${SSH_KEY_USER}/.ssh:/root/.ssh  
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
