- name: Install helm (v3 - no more tiller)
  shell: |
    cd /opt/k3s
    wget https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz
    tar xvf helm-v3.5.4-linux-amd64.tar.gz
    sudo cp linux-amd64/helm /usr/local/bin/

- name: Test helm was successfully installed
  become_user: ubuntu
  command: helm version

- name: Add the repository for official charts
  become_user: ubuntu
  command: helm repo add stable https://charts.helm.sh/stable

- name: Update the chart repository
  become_user: ubuntu
  command: helm repo update

- name: List all available charts from stable repo
  become_user: ubuntu
  command: helm search repo stable

- name: Generate file to verify it passed through this role
  lineinfile:
    dest: /var/log/helm_passed.txt
    line: "{{ ansible_date_time.iso8601 }}"
    state: present
    create: yes
    owner: root
    group: root
    mode: 0644

