- name: Create a directory to run general purpose scripts
  file:
    path: /opt/scripts
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0775
    recurse: yes

- name: copy firewall rules script
  copy: src=firewall-rules.sh dest=/opt/scripts owner=ubuntu group=ubuntu mode=0755

- name: Run firewall rules
  command: bash /opt/scripts/firewall-rules.sh

- name: Reload firewalld to apply the new configuration
  shell:
    firewall-cmd --reload

- name: Print firewalld configuration
  shell:
    firewall-cmd --zone=public --list-all

