defaultEntryPoints = ["http"]
logLevel = "INFO"

sendAnonymousUsage = true

[docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

# enabling api is not absolutely necessary, it is needed only if you need dashboard.
[api]
dashboard = true
entrypoint = "dashboard"


[entryPoints]
  [entryPoints.http]
  address = ":80"

  [entryPoints.dashboard]
  address = ":8080"
