version: '2'

services:
  server:
    image: redash/redash:latest
    command: server
    privileged: true
    depends_on:
      - postgres_redash
      - redis
    ports:
      - "5000:5000"
    env_file: 
      - redash.env    
    restart: unless-stopped
  worker:
    image: redash/redash:latest
    command: scheduler
    privileged: true
    env_file: 
      - redash.env    
    restart: unless-stopped
  redis:
    hostname: redis
    image: redis:3.0-alpine
    restart: unless-stopped
  postgres_redash:
    image: postgres:latest
    container_name: postgres_redash
    hostname: postgres_redash
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - "./shared:/shared"
      - "./utils:/utils"
      - PG_REDASH_DATA:/var/lib/postgresql
      - PG_REDASH_BACKUPS:/backups
    env_file: 
      - redash.env    
  nginx:
    image: redash/nginx:latest
    ports:
      - "8555:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: unless-stopped
    volumes:
      - "./shared:/shared"
      - "/certificates/redash:/etc/certificates"
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"  

volumes:
  PG_REDASH_DATA:
    driver: local
  PG_REDASH_BACKUPS:
    driver: local
