- hosts: all
  # strategy: debug  ## interactive debug console when a task fails.
  roles:
    - gather_custom_facts
    - upgrade
    - {role: docker, when: "ansible_local['docker_facts']['has_docker_installed'] == false" }
    - services
    - reboot
    - cleanup
