--
-- PostgreSQL database dump
--

-- Dumped from database version 10.4 (Debian 10.4-2.pgdg90+1)
-- Dumped by pg_dump version 10.4 (Debian 10.4-2.pgdg90+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: visualizations; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.visualizations VALUES ('2018-07-06 22:09:15.115832+00', '2018-07-06 22:09:15.115832+00', 1, 'TABLE', 1, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:14:35.412813+00', '2018-07-06 22:14:35.412813+00', 3, 'TABLE', 2, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:35:59.140635+00', '2018-07-06 22:35:59.140635+00', 5, 'TABLE', 3, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 7, 'CHART', 3, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:33.480086+00', '2018-07-06 22:39:33.480086+00', 8, 'TABLE', 4, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 10, 'CHART', 4, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:42:18.588062+00', '2018-07-06 22:42:18.588062+00', 12, 'TABLE', 5, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 14, 'CHART', 5, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:45:28.273363+00', '2018-07-06 22:45:28.273363+00', 16, 'TABLE', 6, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:54:36.88336+00', '2018-07-06 22:54:36.88336+00', 20, 'TABLE', 8, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 22, 'CHART', 8, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:02:34.739878+00', '2018-07-06 23:02:34.739878+00', 23, 'TABLE', 9, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 24, 'CHART', 9, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:05:38.263754+00', '2018-07-06 23:05:38.263754+00', 25, 'TABLE', 10, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 26, 'CHART', 10, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:09:06.858147+00', '2018-07-06 23:09:06.858147+00', 29, 'TABLE', 12, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:10:34.222101+00', '2018-07-06 23:10:34.222101+00', 31, 'TABLE', 13, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:15:10.01072+00', '2018-07-06 22:15:10.01072+00', 4, 'CHART', 2, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value_in_mb": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value_in_mb": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:07:38.871851+00', '2018-07-06 23:07:38.871851+00', 27, 'TABLE', 11, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 28, 'CHART', 11, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:08:16.47039+00', '2018-07-22 17:08:16.47039+00', 49, 'TABLE', 22, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:17:33.374291+00', '2018-07-22 17:17:33.374291+00', 55, 'TABLE', 25, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:11:06.126959+00', '2018-07-06 22:11:06.126959+00', 2, 'CHART', 1, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value_in_mb": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value_in_mb": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 17, 'CHART', 6, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:47:11.532833+00', '2018-07-06 22:47:11.532833+00', 18, 'TABLE', 7, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 22:39:19.176508+00', '2018-07-06 22:39:19.176508+00', 19, 'CHART', 7, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 30, 'CHART', 12, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 32, 'CHART', 13, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 16:09:59.263723+00', '2018-07-22 16:09:59.263723+00', 33, 'TABLE', 14, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 34, 'CHART', 14, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 16:12:44.728273+00', '2018-07-22 16:12:44.728273+00', 35, 'TABLE', 15, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 36, 'CHART', 15, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 16:15:01.566339+00', '2018-07-22 16:15:01.566339+00', 37, 'TABLE', 16, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 38, 'CHART', 16, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 16:17:20.336728+00', '2018-07-22 16:17:20.336728+00', 39, 'TABLE', 17, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 40, 'CHART', 17, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 16:18:07.204443+00', '2018-07-22 16:18:07.204443+00', 41, 'TABLE', 18, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 42, 'CHART', 18, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 16:20:04.677273+00', '2018-07-22 16:20:04.677273+00', 43, 'TABLE', 19, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 44, 'CHART', 19, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "line", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"mean_value": {"zIndex": 0, "index": 0, "type": "line", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 16:53:18.196582+00', '2018-07-22 16:53:18.196582+00', 45, 'TABLE', 20, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 46, 'CHART', 20, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:03:09.553013+00', '2018-07-22 17:03:09.553013+00', 47, 'TABLE', 21, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 48, 'CHART', 21, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:12:16.316627+00', '2018-07-22 17:12:16.316627+00', 51, 'TABLE', 23, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 52, 'CHART', 23, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:15:41.782076+00', '2018-07-22 17:15:41.782076+00', 53, 'TABLE', 24, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 54, 'CHART', 24, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 50, 'CHART', 22, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 56, 'CHART', 25, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:20:14.559578+00', '2018-07-22 17:20:14.559578+00', 57, 'TABLE', 26, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 58, 'CHART', 26, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:22:13.715669+00', '2018-07-22 17:22:13.715669+00', 59, 'TABLE', 27, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 60, 'CHART', 27, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:24:15.871729+00', '2018-07-22 17:24:15.871729+00', 61, 'TABLE', 28, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 62, 'CHART', 28, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:26:19.458036+00', '2018-07-22 17:26:19.458036+00', 63, 'TABLE', 29, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 64, 'CHART', 29, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 17:27:49.263759+00', '2018-07-22 17:27:49.263759+00', 65, 'TABLE', 30, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 66, 'CHART', 30, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:08:29.264069+00', '2018-07-22 21:08:29.264069+00', 67, 'TABLE', 31, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 68, 'CHART', 31, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:17:10.673203+00', '2018-07-22 21:17:10.673203+00', 69, 'TABLE', 32, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 70, 'CHART', 32, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:19:06.148939+00', '2018-07-22 21:19:06.148939+00', 71, 'TABLE', 33, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:20:36.505927+00', '2018-07-22 21:20:36.505927+00', 73, 'TABLE', 34, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:25:39.781158+00', '2018-07-22 21:25:39.781158+00', 75, 'TABLE', 35, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 72, 'CHART', 33, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:28:17.696169+00', '2018-07-22 21:28:17.696169+00', 77, 'TABLE', 36, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 78, 'CHART', 36, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:30:28.469755+00', '2018-07-22 21:30:28.469755+00', 81, 'TABLE', 38, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 82, 'CHART', 38, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:55:28.807142+00', '2018-07-22 21:55:28.807142+00', 89, 'TABLE', 42, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 90, 'CHART', 42, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 22:03:38.216782+00', '2018-07-22 22:03:38.216782+00', 91, 'TABLE', 43, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 92, 'CHART', 43, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 22:05:06.883476+00', '2018-07-22 22:05:06.883476+00', 93, 'TABLE', 44, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 94, 'CHART', 44, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 74, 'CHART', 34, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:48:59.391777+00', '2018-07-22 21:48:59.391777+00', 83, 'TABLE', 39, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 84, 'CHART', 39, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:52:58.174326+00', '2018-07-22 21:52:58.174326+00', 85, 'TABLE', 40, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 86, 'CHART', 40, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 22:13:57.986401+00', '2018-07-22 22:13:57.986401+00', 95, 'TABLE', 45, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 96, 'CHART', 45, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"involuntary": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "voluntary": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "type_instance": "series", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 22:24:44.294692+00', '2018-07-22 22:24:44.294692+00', 101, 'TABLE', 48, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 102, 'CHART', 48, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"involuntary": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "voluntary": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "type_instance": "series", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 22:35:21.09865+00', '2018-07-22 22:35:21.09865+00', 103, 'TABLE', 49, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 104, 'CHART', 49, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"involuntary": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "voluntary": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "type_instance": "series", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 76, 'CHART', 35, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:29:07.141445+00', '2018-07-22 21:29:07.141445+00', 79, 'TABLE', 37, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 80, 'CHART', 37, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 21:54:37.536143+00', '2018-07-22 21:54:37.536143+00', 87, 'TABLE', 41, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 88, 'CHART', 41, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": null, "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"minimum": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "maximum": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"minimum": "y", "maximum": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 22:22:03.566195+00', '2018-07-22 22:22:03.566195+00', 97, 'TABLE', 46, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 98, 'CHART', 46, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"involuntary": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "voluntary": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "type_instance": "series", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-22 22:23:28.760614+00', '2018-07-22 22:23:28.760614+00', 99, 'TABLE', 47, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 100, 'CHART', 47, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"involuntary": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "voluntary": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"mean_value": "y", "type_instance": "series", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-23 11:52:51.258342+00', '2018-07-23 11:52:51.258342+00', 105, 'TABLE', 50, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 106, 'CHART', 50, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-23 11:58:47.876419+00', '2018-07-23 11:58:47.876419+00', 107, 'TABLE', 51, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 108, 'CHART', 51, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-23 12:02:14.619396+00', '2018-07-23 12:02:14.619396+00', 109, 'TABLE', 52, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 110, 'CHART', 52, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-23 12:04:33.439617+00', '2018-07-23 12:04:33.439617+00', 111, 'TABLE', 53, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 112, 'CHART', 53, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-23 12:06:57.207973+00', '2018-07-23 12:06:57.207973+00', 113, 'TABLE', 54, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 114, 'CHART', 54, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-23 12:07:53.204783+00', '2018-07-23 12:07:53.204783+00', 115, 'TABLE', 55, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 116, 'CHART', 55, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-23 12:08:47.132995+00', '2018-07-23 12:08:47.132995+00', 117, 'TABLE', 56, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 118, 'CHART', 56, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-23 12:09:50.920719+00', '2018-07-23 12:09:50.920719+00', 119, 'TABLE', 57, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 120, 'CHART', 57, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-23 12:12:15.080658+00', '2018-07-23 12:12:15.080658+00', 121, 'TABLE', 58, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-23 12:14:17.4385+00', '2018-07-23 12:14:17.4385+00', 123, 'TABLE', 59, 'Table', '', '{}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 122, 'CHART', 58, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');
INSERT INTO public.visualizations VALUES ('2018-07-06 23:00:12.933462+00', '2018-07-06 23:00:12.933462+00', 124, 'CHART', 59, 'Chart', '', '{"error_y": {"visible": true, "type": "data"}, "yAxis": [{"type": "linear"}, {"type": "linear", "opposite": true}], "series": {"stacking": "stack", "error_y": {"visible": true, "type": "data"}}, "globalSeriesType": "area", "minColumns": 1, "minRows": 5, "defaultColumns": 3, "sortX": true, "seriesOptions": {"vda": {"zIndex": 0, "index": 0, "type": "area", "yAxis": 0}, "vda1": {"zIndex": 1, "index": 0, "type": "area", "yAxis": 0}}, "xAxis": {"labels": {"enabled": true}, "type": "datetime"}, "columnMapping": {"instance": "series", "mean_value": "y", "time": "x"}, "defaultRows": 8, "customCode": "// Available variables are x, ys, element, and Plotly\n// Type console.log(x, ys); for more info about x and ys\n// To plot your graph call Plotly.plot(element, ...)\n// Plotly examples and docs: https://plot.ly/javascript/", "legend": {"enabled": true}}');


--
-- Name: visualizations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.visualizations_id_seq', 124, true);


--
-- PostgreSQL database dump complete
--

